language: node_js
dist: trusty
cache: yarn
sudo: required

node_js:
    - '7'
    - '8'

before_install:
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2'
    - export PATH="$(yarn global bin):$HOME/.yarn/bin:$PATH"

before_script:
    - 'yarn run build'

after_success:
    - 'yarn run coverage'
