name: deploy

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    build:
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            NPM_USER: ${{ secrets.NPM_USER }}
            NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
            YARN_VERSION: 1.21.0

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@master
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  version: ${{ matrix.node-version }}
            - run: npm install -g yarn@${YARN_VERSION}
            - run: yarn all
            - name: npm publish
              run: |
                  npm set init.author.name "${NPM_USER}"
                  npm set init.author.email "${NPM_EMAIL}"
                  npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
                  npm publish
